# Site settings
title: Daniel Hernández
email: daniel.hernandez.vicente@gmail.com


description: > # this means to ignore newlines until "baseurl:"
 Hi I'm Daniel, a Software craftsman, impulsive reader and challenges accepter.
 This is my personal blog and the place where I'll write about different random stuff.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.danih.ninja" # the base hostname & protocol for your site

twitter_username: danihv10
github_username:  newrol

#Social:
github: https://github.com/newrol
twitter: https://twitter.com/danihv10

# Build settings:
markdown: kramdown

#Collections:
collections:

  itCollection:
    output: true
  
  writingCollection:
    output: true

  notesCollection:
    output: true



images:
  name: image-1.jpg
  name: image-2.jpg
  name: image-3.jpg




