# Site settings
title: Daniel Hernández
description: ''
url: 'http://blog.danihernandez.me'
baseurl: 'http://blog.danihernandez.me'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Daniel Hernández'
  email: daniel.hernandez.vicente.@gmail.com
  twitter_username: danihv10
  github_username:  newrol
  linkedin_username:  danielhv

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
